apiVersion: batch/v1
kind: Job
metadata:
  name: csdapp-db-init
  labels:
    app: csdapp-db-init
spec:
  ttlSecondsAfterFinished: 100
  backoffLimit: 3  # 增加重试次数
  template:
    metadata:
      name: csdapp-db-init
      labels:
        app: csdapp-db-init
    spec:
      restartPolicy: OnFailure
      # 添加容忍度，防止被驱逐
      tolerations:
        - key: "node.kubernetes.io/not-ready"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 300
      containers:
        - name: db-init
          image: crpi-hrvq5w8tkla6visb.cn-beijing.personal.cr.aliyuncs.com/pocobo/csdapp_initsql_job
          env:
            - name: JAVA_OPTS
              value: "-server -Xms6G -Xmx6G -XX:MetaspaceSize=256M -XX:MaxMetaspaceSize=256M -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp/heapdump.hprof"
            # 其他环境变量保持不变
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: DB_HOST
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: DB_USER
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: DB_PORT
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: PASSWORD
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: DB_NAME
            - name: SYS_USER
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: SYS_USER
            - name: SYS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: SYS_PASSWORD
          resources:
            requests:
              memory: "8Gi"
              cpu: "500m"
            limits:
              memory: "8Gi"
              cpu: "1000m"
          # 添加健康检查
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - "ps aux | grep java"
            initialDelaySeconds: 30
            periodSeconds: 10