apiVersion: oceanbase.oceanbase.com/v1alpha1
kind: OBCluster
metadata:
  name: metadb
  namespace: oceanbase
  annotations:
    "oceanbase.oceanbase.com/mode": "service"
spec:
  clusterName: metadb
  clusterId: 1
  userSecrets:
    root: sc-sys-root
    proxyro: sc-sys-proxyro
    monitor: sc-sys-monitor
    operator: sc-sys-operator
  topology:
    - zone: zone1
      replica: 1

  observer:
    image:  crpi-hrvq5w8tkla6visb.cn-beijing.personal.cr.aliyuncs.com/pocobo_docker_io/oceanbase-oceanbase-cloud-native:4.2.1.6-106000012024042515
    resource:
      cpu: 2
      memory: 18Gi
    storage:
      dataStorage:
        storageClass: local-path
        size: 50Gi
      redoLogStorage:
        storageClass: local-path
        size: 50Gi
      logStorage:
        storageClass: local-path
        size: 20Gi
  monitor:
    image: crpi-hrvq5w8tkla6visb.cn-beijing.personal.cr.aliyuncs.com/pocobo_docker_io/oceanbase-oceanbase-obagent:4.2.1-100000092023101717
    resource:
      cpu: 1
      memory: 1Gi
  parameters:
    - name: system_memory
      value: 2G
    - name: obconfig_url
      value: 'http://svc-ob-configserver.oceanbase.svc:8080/services?Action=ObRootServiceInfo&ObCluster=metadb'