kind: Service
apiVersion: v1
metadata:
  labels:
    app: jeecg-boot-nacos
  name: nacos-service
  namespace: csd
spec:
  ports:
    - name: http
      port: 8848
      protocol: TCP
      targetPort: 8848
      nodePort: 30849
  selector:
    app: nacos
  type: NodePort

