# templates/rabbitmq-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-rabbitmq-secret
type: Opaque
data:
  username: {{ .Values.rabbitmq.auth.username | b64enc }}
  password: {{ .Values.rabbitmq.auth.password | b64enc }}
  erlang-cookie: {{ .Values.rabbitmq.auth.erlangCookie | b64enc }}

