---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: oceanbase-system/oceanbase-serving-cert
  labels:
    app.kubernetes.io/component: webhook
    app.kubernetes.io/created-by: ob-operator-generate
    app.kubernetes.io/instance: validating-webhook-configuration
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: validatingwebhookconfiguration
    app.kubernetes.io/part-of: ob-operator-generate
  name: oceanbase-validating-webhook-configuration
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: oceanbase-webhook-service
        namespace: oceanbase-system
        path: /validate-k8s-oceanbase-com-v1alpha1-k8scluster
    failurePolicy: Fail
    name: vk8scluster.kb.io
    rules:
      - apiGroups:
          - k8s.oceanbase.com
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - k8sclusters
    sideEffects: None
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: oceanbase-webhook-service
        namespace: oceanbase-system
        path: /validate-oceanbase-oceanbase-com-v1alpha1-obcluster
    failurePolicy: Fail
    name: vobcluster.kb.io
    rules:
      - apiGroups:
          - oceanbase.oceanbase.com
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - obclusters
    sideEffects: None
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: oceanbase-webhook-service
        namespace: oceanbase-system
        path: /validate-oceanbase-oceanbase-com-v1alpha1-obclusteroperation
    failurePolicy: Fail
    name: vobclusteroperation.kb.io
    rules:
      - apiGroups:
          - oceanbase.oceanbase.com
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - obclusteroperations
    sideEffects: None
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: oceanbase-webhook-service
        namespace: oceanbase-system
        path: /validate-oceanbase-oceanbase-com-v1alpha1-obresourcerescue
    failurePolicy: Fail
    name: vobresourcerescue.kb.io
    rules:
      - apiGroups:
          - oceanbase.oceanbase.com
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - obresourcerescues
    sideEffects: None
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: oceanbase-webhook-service
        namespace: oceanbase-system
        path: /validate-oceanbase-oceanbase-com-v1alpha1-obtenant
    failurePolicy: Fail
    name: vobtenant.kb.io
    rules:
      - apiGroups:
          - oceanbase.oceanbase.com
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - obtenants
    sideEffects: None
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: oceanbase-webhook-service
        namespace: oceanbase-system
        path: /validate-oceanbase-oceanbase-com-v1alpha1-obtenantbackuppolicy
    failurePolicy: Fail
    name: vobtenantbackuppolicy.kb.io
    rules:
      - apiGroups:
          - oceanbase.oceanbase.com
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - obtenantbackuppolicies
    sideEffects: None
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: oceanbase-webhook-service
        namespace: oceanbase-system
        path: /validate-oceanbase-oceanbase-com-v1alpha1-obtenantoperation
    failurePolicy: Fail
    name: vobtenantoperation.kb.io
    rules:
      - apiGroups:
          - oceanbase.oceanbase.com
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - obtenantoperations
    sideEffects: None
